apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: mypage-namespace
spec:                                  
  selector:
    svc: mypage-proflie
  ports:
    - protocol: TCP
      port: 80             # Public-facing port/Service port
      targetPort: 8080       # Container port
      nodePort: 30084
  type: NodePort            # Exposes the service