apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: mypage-namespace  
  labels:
    svc: mypage-proflie
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      svc: mypage-proflie
  template:
    metadata:
      labels:
        svc: mypage-proflie
    spec:
      containers:
        - name: my-userprofile-service
          image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/my-userprofile:latest # Use ECR
          imagePullPolicy: Always
          ports:
          - containerPort: 8080  # Check container's exposed port 
      imagePullSecrets:
        - name: ecr-secret